<?php defined('SYSPATH') OR die('No direct access allowed.');
return array(
	"up" => array(
		"default" => 50
	),
	"cities" => array(
		"default" => 20
	),
	"lider" => array(
		"nizhnevartovsk" => array(
			"kvartiry-i-komnaty" => 8,
			"arenda-kvartir-i-komnat" => 8,
			"inogorodnyaya-i-zarubezhnaya-nedvizhimost" => 8,
			"kommercheskaya-nedvizhimost" => 8,
			"uslugi" => 10,
			"biznes" => 10,
			"stroitelstvo-i-remont" => 10,
			"spetsialisty" => 2,
			"znakomstvo-i-obshenie" => 2,
			"domashnie-zhivotnye-i-rasteniya" => 2,
			"lichnie-veshi" => 2,
			"bitovaya-elektronika" => 2,
			"vakansii" => 5,
			"garazhi-i-stoyanki" => 5,
			"doma-dachi" => 5,
			"zemelnye-uchastki" => 5,
			"avtotransport" => 5,
			"default" => 2
		),
		"default" => array(
			"kvartiry-i-komnaty" => 2,
			"arenda-kvartir-i-komnat" => 2,
			"inogorodnyaya-i-zarubezhnaya-nedvizhimost" => 2,
			"doma-dachi" => 1.5,
			"kommercheskaya-nedvizhimost" => 2,
			"zemelnye-uchastki" => 1.5,
			"garazhi-i-stoyanki" => 1.5,
			"vakansii" => 1.5,
			"spetsialisty" => 1,
			"uslugi" => 2.5,
			"meditsina-zdorove-tovary-i-uslugi" => 1,
			"biznes" => 2.75,
			"stroitelstvo-i-remont" => 2.75,
			"lichnie-veshi" => 1,
			"tovary-dlya-detei" => 1,
			"dlya-doma-i-dachi" => 1,
			"bitovaya-elektronika" => 1.5,
			"znakomstvo-i-obshenie" => 1,
			"sport-otdih-hobby" => 1,
			"domashnie-zhivotnye-i-rasteniya" => 1,
			"prodovolstvennye-tovary" => 1,
			"default" => 1
		),
		"base" => 100
	),
	"premium" => array(
		"nizhnevartovsk" => array(
			"kvartiry-i-komnaty" => 2,
			"arenda-kvartir-i-komnat" => 2,
			"inogorodnyaya-i-zarubezhnaya-nedvizhimost" => 2,
			"doma-dachi" => 1.5,
			"kommercheskaya-nedvizhimost" => 2,
			"zemelnye-uchastki" => 1.5,
			"garazhi-i-stoyanki" => 1.5,
			"vakansii" => 1.5,
			"spetsialisty" => 1,
			"uslugi" => 2.5,
			"meditsina-zdorove-tovary-i-uslugi" => 1,
			"biznes" => 2.75,
			"stroitelstvo-i-remont" => 2.75,
			"lichnie-veshi" => 1,
			"tovary-dlya-detei" => 1,
			"dlya-doma-i-dachi" => 1,
			"bitovaya-elektronika" => 1.5,
			"znakomstvo-i-obshenie" => 1,
			"sport-otdih-hobby" => 1,
			"domashnie-zhivotnye-i-rasteniya" => 1,
			"prodovolstvennye-tovary" => 1,
			"default" => 1
		),

		"default" => array(
			"kvartiry-i-komnaty" => 1.2,
			"arenda-kvartir-i-komnat" => 1.2,
			"inogorodnyaya-i-zarubezhnaya-nedvizhimost" => 1.2,
			"doma-dachi" => 1,
			"kommercheskaya-nedvizhimost" => 1.2,
			"zemelnye-uchastki" => 1,
			"garazhi-i-stoyanki" => 1,
			"vakansii" => 1,
			"spetsialisty" => 0.8,
			"uslugi" => 2,
			"meditsina-zdorove-tovary-i-uslugi" => 0.8,
			"biznes" => 2,
			"stroitelstvo-i-remont" => 2,
			"lichnie-veshi" => 0.8,
			"tovary-dlya-detei" => 0.8,
			"dlya-doma-i-dachi" => 0.8,
			"bitovaya-elektronika" => 1,
			"znakomstvo-i-obshenie" => 0.8,
			"sport-otdih-hobby" => 0.8,
			"domashnie-zhivotnye-i-rasteniya" => 0.8,
			"prodovolstvennye-tovary" => 0.8,
			"default" => 1
		),
		"base" => 100
	),
	"newspaper" => array(
		"tyumen" => array(
			"free" => 0,
			"point" => 120,
			"photo" => 200,
			"green_border" => 258,
			"red_border" => 258,
			"black_border" => 204,
			"blue_border" => 258,
			"yellow_marker" => 216,
			"blue_marker" => 216,
			"red_marker" => 216,
		),
		"surgut" => array(
			"free" => 0,
			"point" => 120,
			"photo" => 200,
			"green_border" => 258,
			"red_border" => 258,
			"black_border" => 204,
			"blue_border" => 258,
			"yellow_marker" => 216,
			"blue_marker" => 216,
			"red_marker" => 216,
		),
		"nizhnevartovsk" => array(
			"free" => 0,
			"point" => 120,
			"photo" => 200,
			"green_border" => 258,
			"red_border" => 258,
			"black_border" => 204,
			"blue_border" => 258,
			"yellow_marker" => 216,
			"blue_marker" => 216,
			"red_marker" => 216,
		)
	)
);