<?php defined('SYSPATH') OR die('No direct access allowed.');

return array(
	'functions' => array(
		'domain'  		=> array('Twig_Functions', 'domain'),
		'debug'  		=>array('Twig_Functions', 'debug'),
		'obj'  		=> array('Twig_Functions', 'obj'),
		'requestblock'  => array('Twig_Functions', 'requestblock'),
		'requestoldview'  => array('Twig_Functions', 'requestoldview'),
		'css' 			=> array('Twig_Functions', 'css'),
		'js' 			=> array('Twig_Functions', 'js'),
		'url' 			=> array('Twig_Functions', 'url'),
		'staticfile' 	=> array('Twig_Functions', 'staticfile'),
		'file_exist' 	=> array('Twig_Functions', 'file_exist'),
		'strim' 	=> array('Twig_Functions', 'strim'),
		'check_object_access' => array('Twig_Functions', 'check_object_access'),
		'get_stat_cached_info' => array('Twig_Functions', 'get_stat_cached_info'),
		'check_access' => array('Twig_Functions', 'check_access'),
		'get_cart_info' => array('Twig_Functions', 'get_cart_info'),
		'get_favorites_info' => array('Twig_Functions', 'get_favorites_info'),
		'get_myobjects_info' => array('Twig_Functions', 'get_myobjects_info'),
		'get_form_element' => array('Twig_Functions', 'get_form_element'),
		'get_config' => array('Twig_Functions', 'get_config'),
		'get_user' =>  array('Twig_Functions', 'get_user'),
		'get_image_paths' => array('Twig_Functions', 'get_image_paths'),
		'get_file' => array('Twig_Functions', 'get_file'),
		'get_date_diff' => array('Twig_Functions', 'get_date_diff'),
		'get_service_icon_info' => array('Twig_Functions', 'get_service_icon_info'),
		'get_request_uri'  => array('Twig_Functions', 'get_request_uri'),
		'requestmethod'  => array('Twig_Functions', 'requestmethod'),
	),
	'filters' => array(
		'contacthide' => array('Twig_Filters', 'contacthide'),
		'values' => array('Twig_Filters', 'values'),
		'formatphone' => array('Twig_Filters', 'formatphone'),
		'phoneico' => array('Twig_Filters', 'phoneico'),
		'mobilephoneico' => array('Twig_Filters', 'mobilephoneico'),
		'emailico' => array('Twig_Filters', 'emailico'),
	),
);