<?php defined('SYSPATH') OR die('No direct access allowed.');

return array(
	'functions' => array(
		'domain'  		=> array ('func' => array('Twig_Functions', 'domain'), 'options' => array() ),
		'debug'  		=> array ('func' => array('Twig_Functions', 'debug'), 'options' => array() ),
		'obj'  		=> array ('func' => array('Twig_Functions', 'obj'), 'options' => array() ),
		'requestblock'  => array ('func' => array('Twig_Functions', 'requestblock'), 'options' => array() ),
		'requestoldview'  => array ('func' => array('Twig_Functions', 'requestoldview'), 'options' => array() ),
		'css' 			=> array ('func' => array('Twig_Functions', 'css'), 'options' => array() ),
		'js' 			=> array ('func' => array('Twig_Functions', 'js'), 'options' => array() ),
		'js_asset' 			=> array ('func' => array('Twig_Functions', 'js_asset'), 'options' => array() ),
		'url' 			=> array ('func' => array('Twig_Functions', 'url'), 'options' => array() ),
		'staticfile' 	=> array ('func' => array('Twig_Functions', 'staticfile'), 'options' => array() ),
		'file_exist' 	=> array ('func' => array('Twig_Functions', 'file_exist'), 'options' => array() ),
		'strim' 	=> array ('func' => array('Twig_Functions', 'strim'), 'options' => array() ),
		'check_object_access' => array ('func' => array('Twig_Functions', 'check_object_access'), 'options' => array() ),
		'get_stat_cached_info' => array ('func' => array('Twig_Functions', 'get_stat_cached_info'), 'options' => array() ),
		'check_access' => array ('func' => array('Twig_Functions', 'check_access'), 'options' => array() ),
		'get_cart_info' => array ('func' => array('Twig_Functions', 'get_cart_info'), 'options' => array() ),
		'get_favorites_info' => array ('func' => array('Twig_Functions', 'get_favorites_info'), 'options' => array() ),
		'get_myobjects_info' => array ('func' => array('Twig_Functions', 'get_myobjects_info'), 'options' => array() ),
		'get_form_element' => array ('func' => array('Twig_Functions', 'get_form_element'), 'options' => array() ),
		'get_config' => array ('func' => array('Twig_Functions', 'get_config'), 'options' => array() ),
		'get_user' =>  array ('func' => array('Twig_Functions', 'get_user'), 'options' => array() ),
		'get_image_paths' => array ('func' => array('Twig_Functions', 'get_image_paths'), 'options' => array() ),
		'get_file' => array ('func' => array('Twig_Functions', 'get_file'), 'options' => array() ),
		'get_date_diff' => array ('func' => array('Twig_Functions', 'get_date_diff'), 'options' => array() ),
		'get_service_icon_info' => array ('func' => array('Twig_Functions', 'get_service_icon_info'), 'options' => array() ),
		'get_request_uri'  => array ('func' => array('Twig_Functions', 'get_request_uri'), 'options' => array() ),
		'get_session_value'  => array ('func' => array('Twig_Functions', 'get_session_value'), 'options' => array() ),
		'requestmethod'  => array ('func' => array('Twig_Functions', 'requestmethod'), 'options' => array() ),
		'is_debug_mode'  => array ('func' => array('Twig_Functions', 'is_debug_mode'), 'options' => array() ),
		'get_userecho_token'   => array ('func' => array('Twig_Functions', 'get_userecho_token'), 'options' => array() ),
		'get_current_city'   => array ('func' => array('Twig_Functions', 'get_current_city'), 'options' => array() ),
		'sameUrlOnAnotherDomain'  		=> array ('func' => array('Twig_Functions', 'sameUrlOnAnotherDomain'), 'options' => array() ),
		'custommenu'  		=> array ('func' => array('Twig_Functions', 'custommenu'), 'options' => array() ),
		'pluk'   => array ('func' => array('Twig_Functions', 'pluk'), 'options' => array() ),
		'get_global'   => array ('func' => array('Twig_Functions', 'get_global'), 'options' => array() ),
		'get_categories'   => array ('func' => array('Twig_Functions', 'get_categories'), 'options' => array() ),
		'repeat'   => array ('func' => array('Twig_Functions', 'repeat'), 'options' => array() ),
		'get_city'   => array ('func' => array('Twig_Functions', 'get_city'), 'options' => array() ),
		'get_meta_robots' => array ('func' => array('Twig_Functions', 'get_meta_robots'), 'options' => array() ),
		'link' => array ('func' => array('Twig_Functions', 'link'), 'options' => array() ),
		'topline_banner_class' => array ('func' => array('Twig_Functions', 'topline_banner_class'), 'options' => array() ),
		'json_encode' => array ('func' => array('Twig_Functions', 'json_encode'), 'options' => array() ),
		'email_link' => array ('func' => array('Twig_Functions', 'email_link'), 'options' => array() ),
	),
	'filters' => array(
		'contacthide' => array('Twig_Filters', 'contacthide'),
		'values' => array('Twig_Filters', 'values'),
		'formatphone' => array('Twig_Filters', 'formatphone'),
		'phoneico' => array('Twig_Filters', 'phoneico'),
		'mobilephoneico' => array('Twig_Filters', 'mobilephoneico'),
		'emailico' => array('Twig_Filters', 'emailico'),
	),
);